gains:
  head_1_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
  head_2_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
#  xtion_frame_joint: {p: 0.5,  d: 0, i: 0, i_clamp: 1.5}

  arm_left_1_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 60}
  arm_left_2_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 50}
  arm_left_3_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 50}
  arm_left_4_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 50}


  arm_right_1_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 60}
  arm_right_2_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 50}
  arm_right_3_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 50}
  arm_right_4_joint: {p: 3000, d: 0, i: 0,   i_clamp: 3, torque_clamp: 50}


  hand_left_fingers_joint: &finger_gains {p: 9.5, d: 0, i: 5, i_clamp: 0}
  hand_left_virtual_1_joint: *finger_gains
  hand_left_virtual_2_joint: *finger_gains

  hand_right_fingers_joint: *finger_gains
  hand_right_virtual_1_joint: *finger_gains
  hand_right_virtual_2_joint: *finger_gains

velocity:
  pid_gains:
     wheel_right_joint: {p: 30,  d: 0, i: 0, i_clamp: 1.0}
     wheel_left_joint:  {p: 30,  d: 0, i: 0, i_clamp: 1.0}
     caster_left_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
     caster_right_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
